# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	MarsMarine-Android-DebugGame  \
	MarsMarine-Android-Development  \
	MarsMarine-Android-Shipping  \
	MarsMarine-Linux-DebugGame  \
	MarsMarine-Linux-Development  \
	MarsMarine-Linux-Shipping  \
	MarsMarine-LinuxArm64-DebugGame  \
	MarsMarine-LinuxArm64-Development  \
	MarsMarine-LinuxArm64-Shipping  \
	MarsMarine \
	MarsMarineEditor-Linux-DebugGame  \
	MarsMarineEditor-Linux-Development  \
	MarsMarineEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MarsMarineEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MarsMarineEditor-Linux-Debug


MarsMarine-Android-DebugGame:
	 $(BUILD) MarsMarine Android DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-Android-Development:
	 $(BUILD) MarsMarine Android Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-Android-Shipping:
	 $(BUILD) MarsMarine Android Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-Linux-DebugGame:
	 $(BUILD) MarsMarine Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-Linux-Development:
	 $(BUILD) MarsMarine Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-Linux-Shipping:
	 $(BUILD) MarsMarine Linux Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-LinuxArm64-DebugGame:
	 $(BUILD) MarsMarine LinuxArm64 DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-LinuxArm64-Development:
	 $(BUILD) MarsMarine LinuxArm64 Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine-LinuxArm64-Shipping:
	 $(BUILD) MarsMarine LinuxArm64 Shipping  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarine: MarsMarine-Linux-Development

MarsMarineEditor-Linux-DebugGame:
	 $(BUILD) MarsMarineEditor Linux DebugGame  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarineEditor-Linux-Development:
	 $(BUILD) MarsMarineEditor Linux Development  -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" $(ARGS)

MarsMarineEditor: MarsMarineEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ernestog/Documents/GameDev/Projects/Unreal Projects/MarsMarine/MarsMarine.uproject" -Game 

.PHONY: $(TARGETS)
